# .goreleaser.yml
# Build customization
builds:
  - binary: telegraf-freeswitch
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - contrib/telegraf-freeswitch.service
